### ISSUE TITLE
Duplicate Arbitrary instances with QuickCheck 2.8.2

### ISSUE THREAD

**Issue by tekul** [factisresearch/graph-core#3]
I got a build failure in travis:

```
Building graph-core-0.2.2.0...
Preprocessing library graph-core-0.2.2.0...
[1 of 4] Compiling Data.Core.Graph.NodeManager ( src/Data/Core/Graph/NodeManager.hs, dist/build/Data/Core/Graph/NodeManager.o )

src/Data/Core/Graph/NodeManager.hs:114:10:
    Duplicate instance declarations:
      instance Arbitrary v => Arbitrary (IM.IntMap v)
        -- Defined at src/Data/Core/Graph/NodeManager.hs:114:10
      instance [safe] Arbitrary a => Arbitrary (IM.IntMap a)
        -- Defined in ‘Test.QuickCheck.Arbitrary’
Updating documentation index
```

It seems this recent QuickCheck change https://github.com/nick8325/quickcheck/issues/62 will break any builds which already have their own `Arbitrary` definitions for these. Perhaps the new instance for `IntMap` can be used instead?

**Comment by agrafix** [comment]
Either that, or adding a newtype wrapper should help... Do you want to give the fix a shot?

**Comment by bergmark** [comment]
I added a revision to keep the default install plan working: https://hackage.haskell.org/package/graph-core-0.2.2.0/revisions/

**Comment by tekul** [comment]
I had a quick look at the code. The instance is defined in `Data.Core.Graph.NodeManager` and differs from the default one in that it only generates positive keys. As it stands, a newtype wrapper would have to be exported from this module which seems messy since it's only used in internal tests. There are only two instances in total, so perhaps it would be better to move the quickcheck code into the test-suite? This would also prevent this kind of error for people who are just installing the library.

**Comment by agrafix** [comment]
Yes, I think moving everything to the test-suite is the way to go. You will then need the newtype wrapper to prevent orphan instances.

**Comment by tekul** [comment]
Oops. Sorry about all the commit msg noise.

**Comment by tekul** [comment]
Any chance you could push a new release at some point? I noticed it also seems to be causing the Spock build to fail.

**Comment by agrafix** [comment]
Sorry I lost track of this. Published the release just now.

**Comment by tekul** [comment]
Thanks!
